### ISSUE TITLE
garbageCollectStaleClusters segfault

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo-mesh#1408]
**Describe the bug**
A sigsev fault in the garbageCollectStaleClusters function

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27efc0d]

goroutine 893 [running]:
github.com/solo-io/gloo-mesh-enterprise/enterprise-networking/pkg/networking/reconciler.(*relayReconciler).garbageCollectStaleClusters(0xc00042f1c0, 0x3ec6a00, 0x0, 0x0)
	/home/runner/work/gloo-mesh-enterprise/gloo-mesh-enterprise/enterprise-networking/pkg/networking/reconciler/enterprise_networking_reconciler.go:168 +0x58d
github.com/solo-io/gloo-mesh-enterprise/enterprise-networking/pkg/networking/reconciler.(*relayReconciler).Reconcile(0xc00042f1c0, 0x3eb0220, 0xc0006b43c0, 0x0, 0x0)
	/home/runner/work/gloo-mesh-enterprise/gloo-mesh-enterprise/enterprise-networking/pkg/networking/reconciler/enterprise_networking_reconciler.go:125 +0x1625
github.com/solo-io/gloo-mesh-enterprise/enterprise-networking/pkg/networking/setup.networkingStarter.startFunc.func1.2.4(0x3eb0220, 0xc0006b43c0, 0x0, 0x0)
	/home/runner/work/gloo-mesh-enterprise/gloo-mesh-enterprise/enterprise-networking/pkg/networking/setup/setup.go:436 +0xb3
```

**To Reproduce**
1. GKE setup with a LoadBalancer istio ingressgateway
2. Register the management cluster.

**Expected behavior**
This should not segfault - and seems to be an easy nil-check fix.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Mesh version = 1.0.0
- Kubernetes version = 1.17
- service mesh and version (if applicable, e.g. Istio 1.7)

**Comment by joekelley** [comment]
This is fixed in Gloo Mesh Enterprise 1.0.2
